name: Build packages for a release

# Controls when the action will run.
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
  workflow_dispatch:

jobs:

  # Run build deploy for linux.
  build-linux:
    name: Build linux artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        id: go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - run: |
          make all
          TRAVIS_OS_NAME=linux ./build/deploy.sh

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: core-geth-*.zip