name: Build packages for a release

# Controls when the action will run.
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
  workflow_dispatch:

jobs:

  # Run build deploy for linux.
  build-linux:
    name: Build artifacts
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: macos-latest
          BUILD_OS_NAME: macos

        - os: ubuntu-latest
          BUILD_OS_NAME: linux

        - os: windows-latest
          BUILD_OS_NAME: windows

    steps:
      - name: Set up Go 1.16
        id: go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Checkout etclabscore/core-geth
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build all packages
        run: make all

      - name: Prepare archive's for release
        run: ./build/deploy.sh
        env:
          BUILD_OS_NAME: ${{ matrix.BUILD_OS_NAME }}

      - name: Upload release sssets
        uses: softprops/action-gh-release@v1
        with:
          files: core-geth*.zip*